import { type ReactNode } from 'react';
import type { Metadata } from 'next';

import { ContentWrapper } from '@/wrappers/ContentWrapper';
import { Header } from '@/components/Header';
import { roboto } from '@/style/fonts';

import './globals.css';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

const RootLayout = ({
  children,
}: Readonly<{
  children: ReactNode;
}>) => {
  return (
    <html lang='cs' className={roboto.className}>
      <body>
        <ContentWrapper>
          <Header />

          {children}
        </ContentWrapper>
      </body>
    </html>
  );
};

export default RootLayout;
